"""empty message

Revision ID: 0e8a2005e86d
Revises: 23fbe682bac0
Create Date: 2022-05-19 00:16:48.368801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e8a2005e86d'
down_revision = '23fbe682bac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('clase', sa.String(length=120), nullable=False),
    sa.Column('faccion', sa.String(length=200), nullable=False),
    sa.Column('raza', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('nombre', table_name='pepe')
    op.drop_index('nombre_2', table_name='pepe')
    op.drop_table('pepe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pepe',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('poder', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nombre_2', 'pepe', ['nombre'], unique=False)
    op.create_index('nombre', 'pepe', ['nombre'], unique=False)
    op.drop_table('personajes')
    # ### end Alembic commands ###
